cask "font-iosevka-sc" do
  version "34.6.1"
  sha256 "a73db4d58ecc376b77d4ae2af3384442a3d0c1f7b5979f54b9a5594c8008f1e0"

  url "https://github.com/smchunn/iosevka-sc/releases/download/v34.6.1/iosevka-sc-v34.6.1.tar.gz"
  name "iosevka-sc"
  desc "Custom build of Iosevka"
  homepage "https://github.com/smchunn/iosevka-sc"

  font "iosevka-sc-Bold.ttf"
  font "iosevka-sc-BoldItalic.ttf"
  font "iosevka-sc-BoldOblique.ttf"
  font "iosevka-sc-Extended.ttf"
  font "iosevka-sc-ExtendedBold.ttf"
  font "iosevka-sc-ExtendedBoldItalic.ttf"
  font "iosevka-sc-ExtendedBoldOblique.ttf"
  font "iosevka-sc-ExtendedItalic.ttf"
  font "iosevka-sc-ExtendedLight.ttf"
  font "iosevka-sc-ExtendedLightItalic.ttf"
  font "iosevka-sc-ExtendedLightOblique.ttf"
  font "iosevka-sc-ExtendedOblique.ttf"
  font "iosevka-sc-Italic.ttf"
  font "iosevka-sc-Light.ttf"
  font "iosevka-sc-LightItalic.ttf"
  font "iosevka-sc-LightOblique.ttf"
  font "iosevka-sc-Oblique.ttf"
  font "iosevka-sc-Regular.ttf"
end
