cask "font-iosevka-sc" do
  version "33.3.4"
  sha256 "b43f11f8518352a8280762f2f27418b1318ca8be500c4a30b690f75894d2473a"

  url "https://github.com/smchunn/iosevka-sc/releases/download/v33.3.4/iosevka-sc-v33.3.4.tar.gz"
  name "iosevka-sc"
  desc "Custom build of Iosevka"
  homepage "https://github.com/smchunn/iosevka-sc"

  font "iosevka-sc-Bold.ttf"
  font "iosevka-sc-BoldItalic.ttf"
  font "iosevka-sc-BoldOblique.ttf"
  font "iosevka-sc-Extended.ttf"
  font "iosevka-sc-ExtendedBold.ttf"
  font "iosevka-sc-ExtendedBoldItalic.ttf"
  font "iosevka-sc-ExtendedBoldOblique.ttf"
  font "iosevka-sc-ExtendedItalic.ttf"
  font "iosevka-sc-ExtendedLight.ttf"
  font "iosevka-sc-ExtendedLightItalic.ttf"
  font "iosevka-sc-ExtendedLightOblique.ttf"
  font "iosevka-sc-ExtendedOblique.ttf"
  font "iosevka-sc-Italic.ttf"
  font "iosevka-sc-Light.ttf"
  font "iosevka-sc-LightItalic.ttf"
  font "iosevka-sc-LightOblique.ttf"
  font "iosevka-sc-Oblique.ttf"
  font "iosevka-sc-Regular.ttf"
end
