cask "font-iosevka-sc-nerd-font" do
  version "33.3.1"
  sha256 "40190e0e7fc96ad6b138710985682d3cc09cd2a9df8365369bc64078d591649f"

  url "https://github.com/smchunn/iosevka-sc/releases/download/v33.3.1/iosevka-sc-nerd-font-v33.3.1.tar.gz"
  name "iosevka-scnf"
  desc "iosevka-scnf custom build patched with Nerd Fonts"
  homepage "https://github.com/smchunn/iosevka-sc"

  font "IosevkaScnfNerdFont-Bold.ttf"
  font "IosevkaScnfNerdFont-BoldItalic.ttf"
  font "IosevkaScnfNerdFont-BoldOblique.ttf"
  font "IosevkaScnfNerdFont-Extended.ttf"
  font "IosevkaScnfNerdFont-ExtendedBold.ttf"
  font "IosevkaScnfNerdFont-ExtendedBoldItalic.ttf"
  font "IosevkaScnfNerdFont-ExtendedBoldOblique.ttf"
  font "IosevkaScnfNerdFont-ExtendedItalic.ttf"
  font "IosevkaScnfNerdFont-ExtendedLight.ttf"
  font "IosevkaScnfNerdFont-ExtendedLightItalic.ttf"
  font "IosevkaScnfNerdFont-ExtendedLightOblique.ttf"
  font "IosevkaScnfNerdFont-ExtendedOblique.ttf"
  font "IosevkaScnfNerdFont-Italic.ttf"
  font "IosevkaScnfNerdFont-Light.ttf"
  font "IosevkaScnfNerdFont-LightItalic.ttf"
  font "IosevkaScnfNerdFont-LightOblique.ttf"
  font "IosevkaScnfNerdFont-Oblique.ttf"
  font "IosevkaScnfNerdFont-Regular.ttf"
end
