cask "font-iosevka-sc" do
  version "33.3.6"
  sha256 "4ef8c5d8f0b78dfa8ec79be8dff092da413232112ccd717abe0b53196779c2dc"

  url "https://github.com/smchunn/iosevka-sc/releases/download/v33.3.6/iosevka-sc-v33.3.6.tar.gz"
  name "iosevka-sc"
  desc "Custom build of Iosevka"
  homepage "https://github.com/smchunn/iosevka-sc"

  font "iosevka-sc-Bold.ttf"
  font "iosevka-sc-BoldItalic.ttf"
  font "iosevka-sc-BoldOblique.ttf"
  font "iosevka-sc-Extended.ttf"
  font "iosevka-sc-ExtendedBold.ttf"
  font "iosevka-sc-ExtendedBoldItalic.ttf"
  font "iosevka-sc-ExtendedBoldOblique.ttf"
  font "iosevka-sc-ExtendedItalic.ttf"
  font "iosevka-sc-ExtendedLight.ttf"
  font "iosevka-sc-ExtendedLightItalic.ttf"
  font "iosevka-sc-ExtendedLightOblique.ttf"
  font "iosevka-sc-ExtendedOblique.ttf"
  font "iosevka-sc-Italic.ttf"
  font "iosevka-sc-Light.ttf"
  font "iosevka-sc-LightItalic.ttf"
  font "iosevka-sc-LightOblique.ttf"
  font "iosevka-sc-Oblique.ttf"
  font "iosevka-sc-Regular.ttf"
end
